// Mock data for CampusConnect app

export const mockUsers = [
  {
    id: '1',
    name: 'Alex Johnson',
    email: 'alex.johnson@stanford.edu',
    college: 'Stanford University',
    major: 'Computer Science',
    year: 'Junior',
    avatar: 'https://randomuser.me/api/portraits/men/32.jpg',
    interests: ['Technology', 'Startups', 'Basketball', 'Photography'],
    bio: 'Passionate about building innovative solutions and capturing moments through my lens.',
    connections: ['2', '3', '5'],
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    name: 'Sarah Williams',
    email: 'sarah.w@mit.edu',
    college: 'MIT',
    major: 'Mechanical Engineering',
    year: 'Senior',
    avatar: 'https://randomuser.me/api/portraits/women/44.jpg',
    interests: ['Robotics', 'Space Exploration', 'Hiking', 'Classical Music'],
    bio: 'Engineering student with a passion for pushing the boundaries of what's possible.',
    connections: ['1', '4'],
    createdAt: '2024-02-20',
  },
  {
    id: '3',
    name: 'Michael Chen',
    email: 'michael.c@berkeley.edu',
    college: 'UC Berkeley',
    major: 'Business Administration',
    year: 'Sophomore',
    avatar: 'https://randomuser.me/api/portraits/men/67.jpg',
    interests: ['Entrepreneurship', 'Finance', 'Soccer', 'Travel'],
    bio: 'Future entrepreneur looking to connect with like-minded individuals to build the next big thing.',
    connections: ['1', '5'],
    createdAt: '2024-03-10',
  },
  {
    id: '4',
    name: 'Emma Rodriguez',
    email: 'emma.r@caltech.edu',
    college: 'Caltech',
    major: 'Physics',
    year: 'Junior',
    avatar: 'https://randomuser.me/api/portraits/women/68.jpg',
    interests: ['Quantum Physics', 'Astronomy', 'Chess', 'Violin'],
    bio: 'Physics enthusiast trying to understand the mysteries of the universe one equation at a time.',
    connections: ['2'],
    createdAt: '2024-01-30',
  },
  {
    id: '5',
    name: 'David Kim',
    email: 'david.k@harvard.edu',
    college: 'Harvard University',
    major: 'Psychology',
    year: 'Senior',
    avatar: 'https://randomuser.me/api/portraits/men/22.jpg',
    interests: ['Behavioral Science', 'Philosophy', 'Meditation', 'Cooking'],
    bio: 'Studying the human mind and behavior to make a positive impact on society.',
    connections: ['1', '3'],
    createdAt: '2024-02-05',
  },
];

export const mockCommunities = [
  {
    id: '1',
    name: 'Tech Enthusiasts',
    description: 'For students passionate about technology, coding, and innovation',
    members: ['1', '2', '3'],
    memberCount: 120,
    category: 'Technology',
    createdAt: '2023-11-15',
  },
  {
    id: '2',
    name: 'Entrepreneurship Club',
    description: 'Connect with fellow entrepreneurs and startup enthusiasts',
    members: ['3', '5'],
    memberCount: 85,
    category: 'Business',
    createdAt: '2023-12-01',
  },
  {
    id: '3',
    name: 'Photography Society',
    description: 'Share your photography skills and learn from others',
    members: ['1'],
    memberCount: 65,
    category: 'Arts',
    createdAt: '2024-01-10',
  },
  {
    id: '4',
    name: 'Astronomy Club',
    description: 'Explore the wonders of the universe together',
    members: ['2', '4'],
    memberCount: 42,
    category: 'Science',
    createdAt: '2024-01-25',
  },
  {
    id: '5',
    name: 'Hiking Group',
    description: 'Outdoor enthusiasts who love hiking and nature',
    members: ['2'],
    memberCount: 58,
    category: 'Sports & Outdoors',
    createdAt: '2024-02-10',
  },
];

export const mockPosts = [
  {
    id: '1',
    userId: '1',
    userName: 'Alex Johnson',
    userAvatar: 'https://randomuser.me/api/portraits/men/32.jpg',
    content: 'Just launched my new app! Would love feedback from fellow developers. #coding #startup',
    image: null,
    likes: 24,
    comments: 8,
    communityId: '1',
    timestamp: '2024-05-15T14:30:00Z',
  },
  {
    id: '2',
    userId: '2',
    userName: 'Sarah Williams',
    userAvatar: 'https://randomuser.me/api/portraits/women/44.jpg',
    content: 'Built a new robot prototype today. The future of automation is exciting!',
    image: 'https://images.unsplash.com/photo-1507146426996-ef05306b995a',
    likes: 42,
    comments: 12,
    communityId: '1',
    timestamp: '2024-05-14T10:15:00Z',
  },
  {
    id: '3',
    userId: '3',
    userName: 'Michael Chen',
    userAvatar: 'https://randomuser.me/api/portraits/men/67.jpg',
    content: 'Looking for co-founders for a new fintech startup. Hit me up if interested!',
    image: null,
    likes: 31,
    comments: 15,
    communityId: '2',
    timestamp: '2024-05-13T16:45:00Z',
  },
  {
    id: '4',
    userId: '4',
    userName: 'Emma Rodriguez',
    userAvatar: 'https://randomuser.me/api/portraits/women/68.jpg',
    content: 'Observed a meteor shower last night. Nature never ceases to amaze me.',
    image: 'https://images.unsplash.com/photo-1464802686167-b939a6910659',
    likes: 56,
    comments: 7,
    communityId: '4',
    timestamp: '2024-05-12T22:30:00Z',
  },
];

export const mockEvents = [
  {
    id: '1',
    title: 'Hackathon 2024',
    description: '48-hour hackathon for students to build innovative solutions',
    date: '2024-06-15',
    time: '09:00',
    location: 'Stanford University',
    organizer: 'Computer Science Department',
    attendees: ['1', '2'],
    maxAttendees: 100,
  },
  {
    id: '2',
    title: 'Startup Pitch Night',
    description: 'Present your startup ideas to investors and get feedback',
    date: '2024-06-20',
    time: '18:30',
    location: 'MIT Campus',
    organizer: 'Entrepreneurship Club',
    attendees: ['3'],
    maxAttendees: 50,
  },
  {
    id: '3',
    title: 'Astrophotography Workshop',
    description: 'Learn to capture the beauty of the night sky',
    date: '2024-06-25',
    time: '20:00',
    location: 'Caltech Observatory',
    organizer: 'Astronomy Club',
    attendees: ['4'],
    maxAttendees: 30,
  },
];

export const mockMessages = [
  {
    id: '1',
    senderId: '1',
    receiverId: '2',
    content: 'Hey Sarah! Loved your robot prototype. Want to collaborate?',
    timestamp: '2024-05-15T10:30:00Z',
  },
  {
    id: '2',
    senderId: '2',
    receiverId: '1',
    content: 'Hi Alex! That sounds great. When are you free to meet?',
    timestamp: '2024-05-15T11:15:00Z',
  },
  {
    id: '3',
    senderId: '1',
    receiverId: '2',
    content: 'How about tomorrow afternoon? Around 2pm?',
    timestamp: '2024-05-15T12:00:00Z',
  },
];

export const mockNotifications = [
  {
    id: '1',
    userId: '1',
    type: 'connection_request',
    message: 'Sarah Williams wants to connect with you',
    timestamp: '2024-05-15T09:30:00Z',
    isRead: false,
  },
  {
    id: '2',
    userId: '1',
    type: 'event_invitation',
    message: 'You're invited to Hackathon 2024',
    timestamp: '2024-05-14T15:45:00Z',
    isRead: true,
  },
  {
    id: '3',
    userId: '1',
    type: 'post_like',
    message: 'Michael Chen liked your post',
    timestamp: '2024-05-14T12:20:00Z',
    isRead: true,
  },
];

export const mockInterests = [
  'Technology',
  'Business',
  'Music',
  'Sports',
  'Art',
  'Photography',
  'Travel',
  'Food',
  'Science',
  'Literature',
  'Gaming',
  'Fashion',
  'Fitness',
  'Movies',
  'Politics',
  'Environment',
  'Health',
  'Education',
  'Startups',
  'Design',
];

export const mockColleges = [
  'Stanford University',
  'MIT',
  'Harvard University',
  'UC Berkeley',
  'Caltech',
  'Yale University',
  'Princeton University',
  'Columbia University',
  'University of Chicago',
  'University of Pennsylvania',
  'Johns Hopkins University',
  'Northwestern University',
  'Duke University',
  'University of Michigan',
  'UC Los Angeles',
  'Cornell University',
  'New York University',
  'University of Virginia',
  'Carnegie Mellon University',
  'University of Southern California',
];